In [1]:
import pandas as pd
data = pd.read_csv('CleanedOpenFoodFacts.csv', sep="\t",low_memory=False)
print("import done")
data.head()

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
import done

,level_0,index,code,created_datetime,last_modified_datetime,pnns_groups_1,nutrition_grade_fr,nutrition-score-fr_100g,energy_100g,fat_100g,carbohydrates_100g,proteins_100g,fiber_100g,salt_100g,sodium_100g,sugars_100g,polyols_100g
0,0,0,3087,2016-09-17 09:17:46+00:00,2016-09-17 09:18:13+00:00,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.59182,NaN,NaN,NaN
1,4,4,16094,2017-03-09 10:34:13+00:00,2017-03-09 10:34:13+00:00,Unknown,NaN,NaN,1552.0,1.43,77.14,8.57,5.7,0.59182,NaN,NaN,NaN
2,6,6,16117,2017-03-09 10:35:30+00:00,2017-03-09 10:35:30+00:00,Unknown,NaN,NaN,1490.0,NaN,80.00,8.89,NaN,0.59182,NaN,NaN,NaN
3,9,9,16513,2017-03-09 10:34:14+00:00,2017-03-09 10:34:14+00:00,Unknown,NaN,NaN,3586.0,100.00,NaN,NaN,NaN,0.59182,NaN,NaN,NaN
4,10,10,16612,2017-03-09 10:35:31+00:00,2017-03-09 10:35:31+00:00,Unknown,NaN,NaN,1393.0,1.04,62.50,22.92,12.5,0.59182,NaN,NaN,NaN

In [2]:
def grams_to_energy(data):
    return data['fat_100g'].values * 37, \
        data['carbohydrates_100g'].values * 17, \
            data['proteins_100g'].values * 17

# energi
data['NRJ_fat'] = data['fat_100g'].values * 37
data['NRJ_carb'] = data['carbohydrates_100g'].values * 17
data['NRJ_prot'] = data['proteins_100g'].values * 17

In [11]:
# make dummies of important categories

# pnns_groups_1
pd.concat([data , data['pnns_groups_1'].str.get_dummies()], 
          axis = 1)

# nutrition_grade_fr
data.loc[data.nutrition_grade_fr.isnull(), 'nutrition_grade_fr'] = 'z'
pd.concat([data , data['nutrition_grade_fr'].str.get_dummies()], 
          axis = 1)